### ISSUE TITLE
JOSM edit link takes me the wrong place

### ISSUE THREAD

**Issue by stevevance** [IndyHurt/where-the-streets-have-no-names#7]
When I click on the JOSM edit link I get taken to OSM.org centered on the wrong place. 

These screenshots show me hovering over two different blue lines, and in the bottom left corner you can see they link to the same URL. 

<img width="1365" alt="screenshot 2015-12-03 13 08 20" src="https://cloud.githubusercontent.com/assets/1330459/11570856/0c770302-99bf-11e5-9558-319d3aeb51e7.png">
<img width="1105" alt="screenshot 2015-12-03 13 08 12" src="https://cloud.githubusercontent.com/assets/1330459/11570858/0c887506-99bf-11e5-84d9-ae4d6f751966.png">

JOSM has a deep linking method that selects the exact way that has the issue.

**Comment by nvkelso** [comment]
@stevevance Thanks for the bug report, will have a look.
